name: 'airbnb'
version: '1.0.0'

profile: 'airbnb'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"]

clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "CREATE TABLE IF NOT EXISTS {{ target.schema }}.audit_log (
      model_name STRING,
      run_timestamp TIMESTAMP
    )"


models:
  airbnb:
    +grants:
      select: ["transform", "reporter"]
    +post-hook:
      - "INSERT INTO {{ target.schema }}.audit_log VALUES ('{{ this }}', CURRENT_TIMESTAMP)"

    +materialized: view

    dim:
      +materialized: table

    src:
      +materialized: ephemeral

    mart:
      +materialized: table

data_tests:
  +store_failures: true
  +schema: _test_failures      

